

export const details = [
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/kashipur19.png",
    //     name:"Kashipur 19",
    //     details:"",
    // },
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/namamisumo.png",
    //     name:"Namami Sumo",
    //     details:"",
    // },
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"G-5",
    //     details:"",
    // },
    {
        crop:"chana",
        season:"rabi",
        image:"/agroseeds/jaki9218.png",
        name:"Jaki-9218",
        details:"",
    },
    {
        crop:"chana",
        season:"rabi",
        image:"/agroseeds/kesari51.png",
        name:"Kesari 51",
        details:"",
    },
    {
        crop:"chana",
        season:"rabi",
        image:"/agroseeds/kesaridollar.png",
        name:"Kesari Dollar",
        details:"",
    },
    {
        crop:"wheat",
        season:"rabi",
        image:"/agroseeds/wheatkesari55.png",
        name:"Kesari 55",
        details:"",
    },
    {
        crop:"wheat",
        season:"rabi",
        image:"/agroseeds/wheatkesari1111.png",
        name:"Kesari 1111",
        details:"",
    },
    {
        crop:"soyabean",
        season:"kharif",
        image:"/agroseeds/soyabeankesari08.png",
        name:"Kesari 08",
        details:"",
    },
    {
        crop:"soyabean",
        season:"kharif",
        image:"/agroseeds/soyabeankesari21.png",
        name:"Kesari 21",
        details:"",
    },
    {
        crop:"maize",
        season:"kharif",
        image:"/agroseeds/maizekesari909.png",
        name:"Kesari 909",
        details:"",
    },
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"JG-11",
    //     details:"",
    // },
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"PKV kabuli 2",
    //     details:"",
    // },
    // {
    //     crop:"Gram",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"vijay",
    //     details:"",
    // },
    // {
    //     crop:"Paddy",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"Namami",
    //     details:"",
    // },
    // {
    //     crop:"Soybean",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"Vaj 99",
    //     details:"",
    // },
    // {
    //     crop:"Soybean",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"KDS 753",
    //     details:"",
    // },
    // {
    //     crop:"Soybean",
    //     season:"kharif",
    //     image:"/agroseeds/",
    //     name:"JS 335",
    //     details:"",
    // },
    
    //     {
    //         crop:"Soybean",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"JS 9305",
    //         details:"",
    //     },
    //     {
    //         crop:"Soybean",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"JS 9560",
    //         details:"",
    //     },
    //     {
    //         crop:"Soybean",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Maus 612",
    //         details:"",
    //     },
    //     {
    //         crop:"Soybean",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"KDS 726",
    //         details:"",
    //     },
    //     {
    //         crop:"Wheat",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Namami 1111",
    //         details:"",
    //     },
    //     {
    //         crop:"Wheat",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Namami 1111",
    //         details:"",
    //     },
    //     {
    //         crop:"Wheat",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"HI 1544",
    //         details:"",
    //     },
    //     {
    //         crop:"Wheat",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"LOK 1",
    //         details:"",
    //     },
    //     {
    //         crop:"Wheat",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Purna Sharbati",
    //         details:"",
    //     },
    //     {
    //         crop:"Urad",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Tau 1",
    //         details:"",
    //     },
    //     {
    //         crop:"Moong",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"PDM 139",
    //         details:"",
    //     },
    //     {
    //         crop:"Toor",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"ICP 8863",
    //         details:"",
    //     },
    //     {
    //         crop:"Maize",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Gangakashi-909",
    //         details:"",
    //     },
    //     {
    //         crop:"Sesame",
    //         season:"kharif",
    //         image:"/agroseeds/",
    //         name:"Gujarat 2",
    //         details:"",
    //     },
  
   
]





export const crops = [
    { key: "soyabean", name: "🫘 Soybean / सोयाबीन" },
    { key: "methi", name: "🌿 Methi / मेथी" },
    { key: "wheat", name: "🌾 Wheat / गेहूं" },
    { key: "chana", name: "🫘 Chana / चना" },
    { key: "maize", name: "🌽 Maize / मक्का" },
    { key: "moong", name: "🟢 Moong / मूंग" },
    { key: "paddy", name: "🌾 Paddy / धान" },
    { key: "sesame", name: "🫒 Sesame / तिल" },
    { key: "toor", name: "🫘 Toor / तूर" },
    { key: "urad", name: "⚫ Urad / उड़द" }
  ];