import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col bg-white`}
      >
        <div className="flex flex-col bg-white min-h-[100vh] pt-[calc(env(safe-area-inset-top)+60px)] " style={{
    backgroundImage: `url("/background.png")`,
    backgroundSize: "cover",      // optional
    backgroundRepeat: "no-repeat", // optional
    backgroundPosition: "center"   // optional
  }}>
        <Navbar/>
        {children}
        </div>
        
      
      </body>
    </html>
  );
}
